# dockerized virtual environment for ELK
version: '3'
services:
  rabbit:
    image: rabbitmq:3.8
    container_name: rabbit01
    hostname: rabbit01
    environment:
      - RABBITMQ_NODENAME=rabbit01
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.56
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./provision/global/etc/localtime:/etc/localtime
      - ./provision/global/etc/timezone:/etc/timezone
    ports:
      - 5672:5672
    networks:
      - rabbitmq

  mgmt:
    image: rabbitmq:3-management
    container_name: rabbit-mgmt
    volumes:
      - ./provision/global/etc/localtime:/etc/localtime
      - ./provision/global/etc/timezone:/etc/timezone
    ports:
      - 8001:15672
    networks:
      - rabbitmq

networks:
  rabbitmq:
    driver: bridge
